version: '3.3'

services:

  biz-application:
    build: 
      context: biz-application
    image: micsigen/vaadin-microservice-biz-application
    volumes:
      - /Users/bmajor/Documents/DEV/GitHub/Microservice/vaadin-microservices-demo/h2-databases:/root/h2-databases
    networks:
     - vaadin-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1

  admin-application:
    build: 
      context: admin-application
    image: micsigen/vaadin-microservice-admin-application
    networks:
     - vaadin-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1

  news-application:
    build:
      context: news-application
    image: micsigen/vaadin-microservice-news-application
    networks:
     - vaadin-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1

networks:

  vaadin-microservice:
    driver: bridge
