version: '3.3'

services:

  monitor-application:
    build: 
      context: monitor-application
    image: micsigen/vaadin-microservice-monitor-application
    ports:
     - "8083:8080"
    networks:
     - vaadin-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1

networks:

  vaadin-microservice:
    driver: bridge
