version: '3.3'

services:

  discovery-server:
    build: 
      context: discovery-server
    image: micsigen/vaadin-microservice-discovery-server
    ports:
     - "8761:8761"
    networks:
     - vaadin-microservice
    deploy:
      replicas: 1

  config-server:
    build: 
      context: config-server
    image: micsigen/vaadin-microservice-config-server
    networks:
     - vaadin-microservice
    depends_on:
     - discovery-server
    deploy:
      replicas: 1

networks:

  vaadin-microservice:
    driver: bridge
