server.port: 8080

spring:
  application.name: config-server
  cloud.config.server.git.uri: https://github.com/micsigen/vaadin-microservices-demo-config.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
